# Generated by Django 4.1.10 on 2023-08-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0002_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(),
        ),
    ]
