# Generated by Django 4.1.10 on 2023-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0005_profile_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defpic.jpg', upload_to='profile_pic'),
        ),
    ]
