# Generated by Django 4.1.10 on 2023-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defpic.jpeg', upload_to='profile_pic'),
        ),
    ]
