# Generated by Django 4.1.10 on 2023-08-29 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0008_alter_profile_bio_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='posts')),
                ('likes', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
