# Generated by Django 4.1.10 on 2023-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0009_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
