# Generated by Django 4.1.10 on 2023-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0010_posts_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='icon',
            field=models.ImageField(default='icon.png', upload_to=''),
        ),
    ]
