# Generated by Django 4.1.10 on 2023-08-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesetup', '0013_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='follow',
            new_name='FollowUser',
        ),
    ]
